namespace EjemploLexer
{
    public enum TokenTypes
    {
        EOF,
        ID,
        Digit,
        PR_PRINT,
        OP_SUM,
        OP_SUB,
        OP_MUL,
        OP_DIV,
        OP_EQU,
        FN_STM,
        Left_Par,
        Right_Par,
        PR_READ,
        LIT_BOOL,
        LIT_STRING,
        PR_FOR,
        PR_WHILE,
        PR_IF,
        PAR_LEFT,
        PAR_RIGHT,
        CB_LEFT,
        CB_RIGHT,
        PR_TO,
        PR_END,
        PR_BEGIN,
        PR_ELSE
    }
}